{% set name = "empath" %}
{% set version = "0.89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91283d9b0233e0cb32c765b9f6274228d20dba9758fae1875e0fb83e4871c40b

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - empath
  commands:
    - pip check

about:
  home: https://github.com/Ejhfast/empath-client
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'analyze text with empath'

  description: |
    Empath is a tool for analyzing text across lexical categories (similar to LIWC), 
    and also generating new lexical categories to use for an analysis.
  dev_url: https://github.com/Ejhfast/empath-client

extra:
  recipe-maintainers:
    - synapticarbors
