travis:
  secure:
    BINSTAR_TOKEN: Zk+lr+s8s1YsycN4diCAdCrCnuscUfJnPoaH/Ek8K2pWYir+qYd04rTobSU4BswtoH1avWfKuxtdXXYznJ/C6zO7x6CooEpYAVJUnMiyUr2L/s/suIx2aWK9kY3WyWbFtTJ3S/u4GWCvE4Hci7fCTdWHF9HCeMxckyLdj5F5/8uQ7MF6pjHW0CCd3hYgXvooCI5HC3oT/FbeDuv5AdJvXtSklWhEt3GsNVlR2D9619+z/VlNdrb8P4ZhoP+tJ4wMpnLro6+pCVeHiGO4hW2Kyth7WTQ3vY64qt4dPQcnzChY6pvLFucm4oq64Me3ltD2j2zycvkyxoS9Nw2uKc814gkLz8+vjRj7zE0G1e4ey/YtaF0OtGUAbo7Q26w0nfl0Q0HPF4Uf2OJwS88wXpWm/aZhyB1HM1d17WqSW7J3zYHBsZ6OiLmJnwQkZ3qRooDa8qLP/sczYFB1fdsh4GBQY8v6x0yrWK6g1cVTbDwNfmX43Tib+LfRlPA/OeCxD19f3kflVJItMpOglMvC4PTUfS59gZvAf+5+LcIC1UUI0Mrlxf+umDiXn1bNBoannEJOPT4P/qKm6QEC16ZT7MtyRjt/rVOaH+Luhvpbg0YG6OxcbeQ4eTBArIT7Z1O+939qFKr1KaDBJ8rgCmLHDWj5V6y27qbM4GGr0LaMhLkygXQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
